# Generated by Django 5.0.2 on 2024-02-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
